/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function triggerManualProxy(enable: boolean, host: string, port: number, bypass: string): void
export declare function triggerAutoProxy(enable: boolean, url: string): void
